platform :ios, '7.0'
pod 'Masonry'
pod 'AFNetworking'
pod 'YTKNetwork'
pod 'SVProgressHUD'
pod 'FMDB'
pod 'JSONModel'
pod 'EDColor'	#设计师颜色
pod 'XXNibBridge', '~> 2.1'
pod 'IQKeyboardManager', '3.2.2'
pod 'QBImagePickerController', '2.5.0'
#pod 'MWPhotoBrowser', '1.4.1'